# Generated by Django 5.2.6 on 2025-10-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_virtualaccount'),
        ('payments', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initiated_by',
            field=models.CharField(blank=True, help_text='Name or identifier of the transaction initiator', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.member'),
        ),
    ]
