# Generated by Django 5.2.6 on 2025-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
