# Generated by Django 5.2.6 on 2025-10-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supportmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccount',
            name='member',
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='chama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='app.chama'),
        ),
    ]
