from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from django.conf import settings
import os

def generate_transaction_receipt(transaction):
    """
    Generates a PDF receipt for a given transaction and returns the file path.
    """

    # file path
    receipts_dir = os.path.join(settings.MEDIA_ROOT, 'receipts')
    os.makedirs(receipts_dir, exist_ok=True)

    file_name = f"receipt_{transaction.mpesa_code}.pdf"
    file_path = os.path.join(receipts_dir, file_name)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 60, "Transaction Receipt")

    # divider
    c.line(50, height - 60, width - 50, height - 60)

    # Transaction Details
    c.setFont("Helvetica", 12)
    y = height - 100

    details = [
        ("Reference Number:", transaction.mpesa_code),
        ("Transaction Type", transaction.get_transaction_type_display()),
        ("Amount (KES)", f"{transaction.amount:,.2f}"),
        ("Member", transaction.member.user.username if transaction.member else "N/A"),
        ("Initiated By", transaction.initiated_by or "System"),
        ("Phone Number", transaction.phone_number),
        ("Status", transaction.status),
        ("Date", transaction.timestamp.strftime("%Y-%m-%d %H:%M:%S")),
    ]

    for label, value in details:
        c.drawString(50, y, f"{label}: {value}")
        y -= 20
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Generated by Chama App")
    c.drawString(50, 35, f"© {transaction.timestamp.year} Chama App. All rights reserved.")

    c.showPage()
    c.save()

    return file_path
